scandipwa/quote-graphql

src/etc/graphql/events.xml
Fixes Catalog Price Rules not being applied.
=> Add missing observer

src/Model/Customer/CheckCustomerAccount.php, src/Model/Resolver/ExpandedOrderResolver.php, src/Model/Resolver/OrderListResolver.php, src/Model/Resolver/ProductResolver.php, src/etc/schema.graphqls
Added support for graphql-orders.
=> Added support for graphql-orders.

src/etc/schema.graphqls
Creating a PR as asked, but this integration is a work in progress, though changes are unlikely to this PR.
Adds an additional field to PaymentMethodInput for stripe integration.
(I have pulled changes from the braintree branch, since the same field is required, to avoid conflicts in the future.)
=> Stripe integration

src/Model/Customer/MergeCustomerAndGuestQuotes.php, src/Observer/MergeCustomerAndGuestQuotes.php, src/etc/graphql/events.xml
Depends on:
https://github.com/scandipwa/customer-graph-ql/pull/5
https://github.com/scandipwa/base-theme/pull/339
=> Merge guest and customer quote on customer login

src/Model/Resolver/GetCartForCustomer.php, src/Model/Resolver/SaveAddressInformation.php
Implement subtotal including tax retrieval, fix grand total being calculated incorrectly
=> Totals in checkout

src/Model/Resolver/GetCartForCustomer.php, src/Model/Resolver/SaveCartItem.php
This PR is a duplicate-fix of #30
=> Cart and Minicart don't respect out of stock threshold

src/Model/Resolver/GetCartForCustomer.php, src/Model/Resolver/SaveCartItem.php, src/etc/schema.graphqls
Related PR:
- https://github.com/scandipwa/base-theme/pull/705
- https://github.com/scandipwa/catalog-graphql/pull/63
=> SWPWA-496 - Bundle products

src/Model/Resolver/SaveCartItem.php
Apply customizable options to products with types simple, virtual, and configurable.
https://github.com/scandipwa/base-theme/issues/840
=> SWPWA-639 configurable product customizable options fix

src/Model/Resolver/CartDisplayConfigResolver.php, src/Model/Resolver/GetCartForCustomer.php, src/etc/schema.graphqls
Issue scandipwa/base-theme#1364
=> Respect M2 tax display setting to show prices with taxes

src/Model/Resolver/BraintreeResolver.php, src/etc/schema.graphqls
Original issue: [1024](https://github.com/scandipwa/base-theme/issues/1024)
Unable to pay when enabling 3d security for braintree
Added resolver to get whether or not braintree 3d security is enabled.
=> #1024 3d security support for braintree

src/Model/Resolver/GetCartForCustomer.php
Fixed an issue when cart item removal request responded with an error
=> Cart item removal issue

src/Model/Resolver/ProductResolver.php
Fixes scandipwa/base-theme#1566
=> Fixed order info request error

src/etc/schema.graphqls
Fixes scandipwa/base-theme#1499
=> Show VAT Number on Storefront

src/etc/schema.graphqls
Fixes scandipwa/base-theme#1499
=> Fixed vat_id field issue

src/Model/Resolver/EstimateShippingCosts.php
Original issue: [#1568](https://github.com/scandipwa/scandipwa/issues/1568)
* Updates Store Id when getting shipping method data.
* Store Id update is located inside class EstimateShippingCosts instead of GetCartForCustomers, because requests to capture quote data are not sequentially, thus updating store ID within GetCartForCustomers will not update EstimateShippingCosts quotes store_id on first request.
=> #1568 Correct shipping method between store switching

src/Model/Resolver/GetCartForCustomer.php
Fixes scandipwa/scandipwa#1796
Added shipping tax amount field
=> Shipping Tax Amount Backend

src/Model/Resolver/CartDisplayConfigResolver.php, src/Model/Resolver/GetCartForCustomer.php, src/etc/schema.graphqls
Fixes scandipwa/scandipwa#1900
Added totals, taxes and shipping values in order to correctly display them on the frontend.
=> Cart and Checkout Totals, Taxes, Shipping Backend

src/Model/Resolver/ExpandedOrderResolver.php, src/etc/schema.graphqls
Fixes scandipwa/scandipwa#2117
=> Added shipping_incl_tax to order

src/Model/Resolver/GetCartForCustomer.php, src/Model/Resolver/SaveCartItem.php, src/etc/schema.graphqls
Original issue: [2269](https://github.com/scandipwa/scandipwa/issues/2269)
In this PR:
* Added getter and setter for downloadable product links.
=> #2269 Support for downloadable product links

src/Model/Resolver/LinkOrder.php, src/etc/schema.graphqls
Original issue: [#2148](https://github.com/scandipwa/scandipwa/issues/2148)
* Created new mutation to link order to customer after order is placed.
=> #2148 Linkage of order to customer via graphql

src/Model/Resolver/SaveCartItem.php, src/etc/schema.graphqls
Original issue: https://github.com/scandipwa/scandipwa/issues/1876
In this PR:
* Adds support to place order via passed information from info_buyRequest, that wishlist item uses.
=> #1876 Support to place order via info_buyRequest

src/Model/Resolver/SaveCartItem.php
Fixes scandipwa/scandipwa#1793
Fixed cart item quantity change for backorders products.
=> Cart Backorders Items

src/Model/Resolver/GetStores.php
fixes scandipwa/scandipwa#1506
=> issue-1506 - Transform string to int

src/Model/Resolver/ProductResolver.php
Fixes scandipwa/scandipwa#2271
Fixed issue when deleted product is not found in the product data.
=> Order popup BE

src/Model/Resolver/ProductResolver.php
Fixes scandipwa/scandipwa#2758
Added title and image placeholder from the missing product.
=> Missing Product Fix BE

src/Model/Resolver/ProductResolver.php
Fixes scandipwa/scandipwa#2821
Added missing image field.
Added area emulation in order to get area specific placeholders then get them directly by url from media.
=> Missing Image Field Issue

src/Model/Resolver/SaveCartItem.php
**Original issue:**
* https://github.com/scandipwa/scandipwa/issues/3023
**Problem**:
* When adding bundle product to cart - Magento generates new SKU, that doesn't have stock data, so when requesting stock quantity we will receive it as value 0, thus check if requested qty < stock qty will always return error message: `Provided quantity exceeds stock limits`
**In this PR:**:
* Spliced logic so that bundle products use native Magento graphql quantity changer.
=> #3023 Bundle product quantity changer

src/Model/Resolver/SaveCartItem.php
Original issue:
* https://github.com/scandipwa/scandipwa/issues/2757
Problem:
* Missing interpreter for customizable options on Downloadable type
In this PR:
* Added interpreter for customizable options on Downloadable type
=> Downloadable pruduct support for customizable options

src/Model/Resolver/GetCartForCustomer.php, src/Model/Resolver/GetStores.php, src/etc/schema.graphqls
Fixes https://github.com/scandipwa/scandipwa/issues/3156
=> issue-3156 - Set correct pagesize for fetching stores and get is available instore for cart

src/Model/Bundle/Type.php, src/Model/Cart/BuyRequest/BundleDataProvider.php, src/Model/Quote/Item/Processor.php, src/etc/di.xml
* Solves issue for magento `addProductsToCart` query where bundle product with multiple selected options only adds last one.
=> Bundle multi-option select fix

src/Model/Resolver/GetCartForCustomer.php, src/etc/schema.graphqls
**Original issue:**
* Fixes https://github.com/scandipwa/scandipwa/issues/3391
**Problem:**
* OrderData is not returning cart id (masked)
* Added support for id - for OrderData
=> #3391 Added cart id to OrderData

src/Model/Resolver/GetCartForCustomer.php, src/etc/schema.graphqls
**Problem**
Couldn't fetch shipping_address
**In this PR**
Added shipping_address to cartData (GetCartForCustomer) to be fetched on reloading /checkout
For this PR https://github.com/scandipwa/scandipwa/pull/4621
*No extra request will be created, the data will be fetched with the original initial cartData fetching*.
=> Added shipping_address to cartData (GetCartForCustomer)

src/Model/Resolver/GetCartForCustomer.php, src/etc/schema.graphqls
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3763
**Problem:**
* Whether the minimum order amount has been reached is checked only at the payment step
* Check if the minimum order amount has been reached at the cart level
=> #3763 - Get the minimum order amount for a purchase

src/Model/Resolver/OrderListResolver.php
Removed unnecessary parent constructor call since it produced the error.
=> Parent Constructor Call Fix

src/Model/Resolver/ExpandedOrderResolver.php, src/Model/Resolver/OrderListResolver.php
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/2685
=> #2685 - Revert previous solution

src/Model/Resolver/CartItems.php
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/3701
**Problem:**
* Product don`t have salable qty
* Call post processor for products
=> #3701 - Add salable qty to cart product

src/Model/Resolver/GetPaymentMethods.php
**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4802
**Problem:**
* All enabled payment methods are shown on billing step if price total 0
* Only 'Zero Subtotal Checkout' payment method is shown on billing step if price total 0
=> #4802 - Return only free payment if available
